[package]
name = "imgzen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["derive", "env"] }
globset = "0.4"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
lol_html = "3.0"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.4"
humansize = "2.1"
ravif = "0.13"
imgref = "1.12"
webp = "0.3"
oxipng = "9.0"
rgb = "0.8"
mozjpeg = "0.10"
